# Generated by Django 4.2.7 on 2023-11-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='random_filed',
            field=models.DateField(default='2022-11-11'),
            preserve_default=False,
        ),
    ]
