# Generated by Django 4.2.7 on 2023-11-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_random_filed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='random_filed',
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
